name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build the executable
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bulkpr-${{ matrix.os }}-${{ matrix.arch }} main.go

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bulkpr-executable-${{ matrix.os }}-${{ matrix.arch }}
          path: bulkpr-${{ matrix.os }}-${{ matrix.arch }}
